<a href="https://colab.research.google.com/github/jeongkeona/bigdata/blob/main/R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a<-c(3)
a

[1] 3

In [ ]:
#1.데이터유형

#1.vector
#  v1 <- c(-1,0,1)
#  v2 <- c("Hello","Hi")

#2.matrix
# A = [1,2,3,4,5,6,7,8,9] 3x3
# x <- c(1,2,3,4,5,6,7,8,9)
# A <- matrix(x,nrow=3,ncol=3)

#3.array
#xx <- c(1,2,3,4,5,6)
#arr <- array(xx,dim=c(2,2,3))
#arr[행,열,1]
#arr[,,2]
#arr[,,3]

#4.list : 집합
#a=c(1,2,3,"Hello"."Hi")

#5.data.frame
# sex F F M M F F M F F M age 30 23 25 56 54 43 37 43 34 34 area 제주 서울 서울 경기 제주 인천 경기 인천 제주 제주 
#SEX<-c("F","F","M","M","F","F","M","F","F","M")
#AGE<-c(30,23,25,56,54,43,37,43,34,34)
#AREA<-c("제주","서울","서울","경기","제주","인천","경기","인천","제주","제주")
#f<-data.frame(SEX,AGE,AREA)

In [ ]:
#2.벡터의 유형
# num : 숫자형
# str(ID)
# str(AGE)
# mode() : 타입 - numerir,character,factor
# length() : 길이,데이터 갯수
# chr : 문자형
# Bool : 논리형 or logical
# factor : 범주형 - 척도, 명목형
# - 예) 과일 : apple,banana,cherry


In [ ]:
x <- c(1,2,3,4,5,6,7,8,9)
A <- matrix(x,nrow=3,ncol=3)
A

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [ ]:
x <- c(1,2,3,4,5,6,7,8,9)
B <- matrix(x,nrow=3,ncol=3,byrow=T)
B

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [ ]:
xx <- c(1,2,3,4,5,6)
arr <- array(xx,dim=c(2,2,3))
arr[,,1]
arr[,,2]
arr[,,3]

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[,1] [,2]
[1,] 5    1   
[2,] 6    2

[,1] [,2]
[1,] 3    5   
[2,] 4    6

In [ ]:
SEX<-c("F","F","M","M","F","F","M","F","F","M")
AGE<-c(30,23,25,56,54,43,37,43,34,34)
AREA<-c("제주","서울","서울","경기","제주","인천","경기","인천","제주","제주")
f<-data.frame(SEX,AGE,AREA)
str(f)

'data.frame':	10 obs. of  3 variables:
 $ SEX : chr  "F" "F" "M" "M" ...
 $ AGE : num  30 23 25 56 54 43 37 43 34 34
 $ AREA: chr  "제주" "서울" "서울" "경기" ...


In [ ]:
str(f$AGE)

 num [1:10] 30 23 25 56 54 43 37 43 34 34


In [ ]:
mode(AREA)

[1] "character"

In [ ]:
frute<-c("apple","banana","banana","cherry","cherry","cherry","banana","apple","apple","banana")
frute<-factor(frute, labels = c("apple","banana","cherry"))
str(frute)

 Factor w/ 3 levels "apple","banana",..: 1 2 2 3 3 3 2 1 1 2


In [ ]:
f$SEX<-factor(SEX, labels = c("F","M"))
str(f)

'data.frame':	10 obs. of  3 variables:
 $ SEX : Factor w/ 2 levels "F","M": 1 1 2 2 1 1 2 1 1 2
 $ AGE : num  30 23 25 56 54 43 37 43 34 34
 $ AREA: chr  "제주" "서울" "서울" "경기" ...


In [ ]:
f$AREA<-factor(AREA, labels = c("제주","서울","경기","인천"))
str(f)

'data.frame':	10 obs. of  3 variables:
 $ SEX : Factor w/ 2 levels "F","M": 1 1 2 2 1 1 2 1 1 2
 $ AGE : num  30 23 25 56 54 43 37 43 34 34
 $ AREA: Factor w/ 4 levels "제주","서울",..: 4 2 2 1 4 3 1 3 4 4


조건문/반복문

In [ ]:
x<-1:10
y<-10:1

In [ ]:
print(x)

 [1]  1  2  3  4  5  6  7  8  9 10


In [ ]:
print(y)

 [1] 10  9  8  7  6  5  4  3  2  1


In [ ]:
#조건문 연산자 +
#              -
#              *   
#              / 
#              %% : 나머지
#              %/% : 정수 나누기(몫)
#              ** or ^ 제곱수 

#관계 연산자(TRUE or FALSE)
#           >
#           >= 크거나 같다  
#           <
#           <= 작거나 같다
#           == 같다
#           =! 같지않다
#           ! 다르다

#논리 연산자
#      & 그리고
#      : 또는

In [3]:
a<-8
if(a %% 2 == 0){
    print("짝수")
}else{
    print("홀수")
}

[1] "짝수"


과제

In [ ]:
##1.세 수 중 가장 큰 수 출력
a<-4
b<-5
c<-1
if(a>b&c){
    print(a)
}else if(b>c&a){
    print(b)
}else{
    print(c)
}
    


[1] 5


In [30]:
#2.내림차순 출력
a<-4
b<-5
c<-1
if(a>b>c){
    print(a,b,c)
}else if(b>c>a){
    print(b,c,a)
}else if(c>a>b){
    print(c,a,b)
}else if(a>c>b){
    print(a,c,b)
}else if(b>a>c){
    print(b,a,c)
}else{
    print(c,b,a)
}


ERROR: ignored

In [ ]:
#3.윤년검색기
잘모르겠습니다

In [23]:
##4.구구단 출력
a<-2
for(i in 1:9){
    print(a*i)
}

[1] 2
[1] 4
[1] 6
[1] 8
[1] 10
[1] 12
[1] 14
[1] 16
[1] 18


In [ ]:
##5.1~100 총합 구하기
sum <- 0
for(i in 1:100){
   sum <- sum+i
   print(sum)
}

In [10]:
##6.1~5 순차곱 구하기
a <- 5
sum <- 1
for(i in 1:a){
  sum <- sum*i 
}
sum

[1] 120

In [18]:
##7.1~100 짝수/홀수 출력
for(i in 1:100){
  if(i%%2 == 0){
      print("짝수")}
else{print("홀수")}
}

[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"
[1] "홀수"
[1] "짝수"


In [16]:
##8.5의 배수 출력
for(i in 1:100){
  if(i%%5 == 0){print(i)
  }else{print("x")}
}

[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 5
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 10
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 15
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 20
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 25
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 30
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 35
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 40
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 45
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 50
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 55
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 60
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 65
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 70
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 75
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 80
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 85
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 90
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 95
[1] "x"
[1] "x"
[1] "x"
[1] "x"
[1] 100


In [24]:
##9.2와3의 공배수
for(i in 1:100){
  if(i%%2 == 0&i%%3 == 0){print("2,3의 공배수")
  }else{print("2,3의 공배수가 아님")}
}

[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수가 아님"
[1] "2,3의 공배수"
[1] "2,3의 

In [13]:
##10.평균구하기
sum <- 0
for(i in 1:100){
  sum <- sum + i
}
print(sum/100)

[1] 50.5
